# Generated by Django 4.2.1 on 2023-06-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_rename_name_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='courses',
            new_name='course',
        ),
    ]
