# Generated by Django 4.2.1 on 2023-06-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_rename_courses_comment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='desc',
        ),
    ]
