# Generated by Django 4.2.1 on 2023-06-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_regestration_app', '0001_initial'),
        ('favorite_books_app', '0002_book_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='favorites',
            field=models.ManyToManyField(related_name='books', to='login_and_regestration_app.user'),
        ),
    ]
