# Generated by Django 4.2.1 on 2023-06-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deletable',
            field=models.BooleanField(default='True'),
        ),
    ]
