# Generated by Django 4.2.1 on 2023-06-23 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_regestration_app', '0001_initial'),
        ('kickball_league_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='login_and_regestration_app.user'),
        ),
    ]
