# Generated by Django 4.2.1 on 2023-06-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickball_league_app', '0002_team_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='game_day',
            field=models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('yhursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], default='Sunday', max_length=45),
        ),
    ]
