# Generated by Django 4.2.1 on 2023-06-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickball_league_app', '0003_alter_team_game_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='player_count',
            field=models.IntegerField(default=0),
        ),
    ]
