# Generated by Django 4.2.1 on 2023-06-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickball_league_app', '0004_team_player_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='game_day',
            field=models.CharField(default='Sunday', max_length=45),
        ),
    ]
