# Generated by Django 4.2.1 on 2023-06-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickball_league_app', '0005_alter_team_game_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
